"""
Train & Convert: Touch Gesture TinyML Model
---------------------------------------------
Step 2 + 3 of the pipeline:
  1. Loads the CSVs recorded by collect_touch_data.py
  2. Trains a tiny neural network to classify the gesture windows
  3. Quantizes it to int8 (TFLite Micro requires this to fit ESP32 RAM)
  4. Exports it as a C header file (model_data.h) ready to embed in an
     Arduino sketch

Install dependencies first:
    pip install tensorflow numpy

Run:
    python train_model.py
"""

import os
import glob
import csv
import numpy as np
import tensorflow as tf

# ---------------- CONFIG ----------------
DATA_DIR = "touch_data"          # must match OUTPUT_DIR in collect_touch_data.py
WINDOW_SAMPLES = 50               # must match WINDOW_SAMPLES used during collection
TEST_SPLIT = 0.2
EPOCHS = 60
OUTPUT_HEADER = "model_data.h"
OUTPUT_TFLITE = "model.tflite"
# -----------------------------------------


def load_dataset():
    X, y, labels = [], [], []
    csv_paths = sorted(glob.glob(os.path.join(DATA_DIR, "*.csv")))
    if not csv_paths:
        raise FileNotFoundError(f"No CSVs found in {DATA_DIR}/ -- run collect_touch_data.py first")

    for path in csv_paths:
        label_name = os.path.splitext(os.path.basename(path))[0]
        if label_name not in labels:
            labels.append(label_name)
        label_idx = labels.index(label_name)

        with open(path, newline="") as f:
            reader = csv.reader(f)
            header = next(reader)
            for row in reader:
                values = [float(v) for v in row[1:]]  # row[0] is the label column
                if len(values) != WINDOW_SAMPLES:
                    continue  # skip malformed rows
                X.append(values)
                y.append(label_idx)

    X = np.array(X, dtype=np.float32)
    y = np.array(y, dtype=np.int64)
    print(f"Loaded {len(X)} samples across {len(labels)} classes: {labels}")
    for i, name in enumerate(labels):
        print(f"  {name}: {(y == i).sum()} reps")
    return X, y, labels


def normalize(X, data_min, data_max):
    span = max(data_max - data_min, 1e-6)
    return (X - data_min) / span


def split_train_test(X, y, test_split):
    n = len(X)
    idx = np.random.permutation(n)
    n_test = int(n * test_split)
    test_idx, train_idx = idx[:n_test], idx[n_test:]
    return X[train_idx], y[train_idx], X[test_idx], y[test_idx]


def build_model(input_size, num_classes):
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(input_size,)),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(8, activation="relu"),
        tf.keras.layers.Dense(num_classes, activation="softmax"),
    ])
    model.compile(optimizer="adam",
                  loss="sparse_categorical_crossentropy",
                  metrics=["accuracy"])
    return model


def quantize_to_tflite(model, x_train):
    def representative_dataset():
        for i in range(min(200, len(x_train))):
            yield [x_train[i:i + 1].astype(np.float32)]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    return converter.convert()


def write_c_header(tflite_bytes, labels, data_min, data_max, path):
    var_name = "g_model"
    with open(path, "w") as f:
        f.write("// Auto-generated by train_model.py -- do not edit by hand\n")
        f.write("#pragma once\n\n")
        f.write(f"#define MODEL_INPUT_SIZE {WINDOW_SAMPLES}\n")
        f.write(f"#define MODEL_NUM_CLASSES {len(labels)}\n")
        f.write(f"#define MODEL_NORM_MIN {data_min}f\n")
        f.write(f"#define MODEL_NORM_MAX {data_max}f\n\n")

        f.write("const char* MODEL_LABELS[MODEL_NUM_CLASSES] = {\n")
        f.write(", ".join(f'"{l}"' for l in labels))
        f.write("\n};\n\n")

        f.write(f"alignas(8) const unsigned char {var_name}[] = {{\n")
        for i in range(0, len(tflite_bytes), 12):
            chunk = tflite_bytes[i:i + 12]
            f.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write("};\n")
        f.write(f"const unsigned int {var_name}_len = {len(tflite_bytes)};\n")

    print(f"Wrote {path} ({len(tflite_bytes)} bytes model)")


def main():
    X, y, labels = load_dataset()

    data_min, data_max = float(X.min()), float(X.max())
    X_norm = normalize(X, data_min, data_max)

    X_train, y_train, X_test, y_test = split_train_test(X_norm, y, TEST_SPLIT)

    model = build_model(WINDOW_SAMPLES, len(labels))
    model.fit(X_train, y_train, epochs=EPOCHS, validation_data=(X_test, y_test), verbose=2)

    loss, acc = model.evaluate(X_test, y_test, verbose=0)
    print(f"\nTest accuracy: {acc:.2%}")

    tflite_bytes = quantize_to_tflite(model, X_train)
    with open(OUTPUT_TFLITE, "wb") as f:
        f.write(tflite_bytes)
    print(f"Wrote {OUTPUT_TFLITE} ({len(tflite_bytes)} bytes)")

    write_c_header(tflite_bytes, labels, data_min, data_max, OUTPUT_HEADER)
    print("\nDone. Copy model_data.h into your Arduino sketch folder for the deployment step.")


if __name__ == "__main__":
    main()